language: node_js
node_js: node
cache: npm
addons:
  firefox: lastest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - npm run codecov